version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
      python: 3.11
    commands:
    - npm install --location=global npm@^9
    - pyenv install -s 3.8 3.9
    - pyenv global $PYTHON_311_VERSION 3.9 3.8
    - python -m pip install -U pip setuptools poetry tox
    - npm ci
  pre_build:
    commands:
    - cd ./deployment
    - ./build-open-source-dist.sh
    - cd ..
    - npm run test:ci
  build:
    commands:
    - cd ./deployment
    - ./build-s3-dist.sh $DIST_OUTPUT_BUCKET $SOLUTION_NAME $VERSION
    - cd ..
  post_build:
    commands:
    - rm ./deployment/global-s3-assets/instance-scheduler-on-aws-testing-pipeline.template
    - rm ./deployment/global-s3-assets/instance-scheduler-on-aws-testing-pipeline-*.template
    - rm ./deployment/global-s3-assets/instance-scheduler-on-aws-end-to-end-testing-*.template
artifacts:
  files:
  - '**/*'
  exclude-paths:
  - '**/.mypy_cache/**/*'
  - '**/__pycache__/**'
  - '**/.tox/**/*'
